FROM python:3.12-slim

# 设置工作目录
WORKDIR /app

# 复制依赖文件
COPY ./backend/requirements.txt .

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 复制后端代码
COPY ./backend .

# 启动命令
CMD ["python", "main.py"]