#!/usr/bin/env python3
"""Generate SimplifiedChineseMapping.swift from OpenCC Traditional->Simplified tables.

Input files (Apache-2.0, https://github.com/BYVoid/OpenCC):
  TSCharacters.txt - traditional char -> simplified candidates
  TSPhrases.txt    - traditional phrase -> simplified candidates

The generated Swift file embeds the tables so the packaged macOS app can normalize
Chinese transcripts to Simplified Chinese (zh-CN) without any runtime dependency.
Do not edit the generated file by hand; regenerate with this script.

Usage:
  python3 scripts/generate-simplified-chinese-mapping.py \
      --characters /path/to/TSCharacters.txt \
      --phrases /path/to/TSPhrases.txt \
      --output desktop-macos/Sources/PromptMeet/Transcription/SimplifiedChineseMapping.swift
"""

import argparse
from pathlib import Path


def parse_table(path: Path) -> list[tuple[str, str]]:
    """Parse OpenCC TS table lines: key<TAB>value1 value2 ... (first value is default)."""
    entries: list[tuple[str, str]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        key, _, values = line.partition("\t")
        key = key.strip()
        values = values.split()
        if not key or not values:
            continue
        entries.append((key, values[0]))
    return entries


def swift_string_literal(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--characters", required=True, type=Path)
    parser.add_argument("--phrases", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    characters = parse_table(args.characters)
    phrases = parse_table(args.phrases)
    # Longest phrases first so the normalizer applies longest-match substitutions.
    phrases.sort(key=lambda pair: len(pair[0]), reverse=True)

    def emit_entries(prefix: str, entries: list[tuple[str, str]], value_formatter):
        body = [f"        {prefix} {value_formatter(key, value)}," for key, value in entries]
        if body:
            body[-1] = body[-1].rstrip(",")
        return body

    lines = [
        "// swiftlint:disable file_length type_body_length",
        "// Auto-generated from OpenCC Traditional->Simplified dictionaries (Apache-2.0).",
        "// Sources: https://github.com/BYVoid/OpenCC (TSCharacters.txt, TSPhrases.txt)",
        f"// Generated by scripts/generate-simplified-chinese-mapping.py; characters={len(characters)}, phrases={len(phrases)}.",
        "// Do not edit by hand - regenerate with the generator script.",
        "",
        "enum SimplifiedChineseMapping {",
        "    /// Traditional -> simplified character pairs (first candidate from OpenCC).",
        "    static let characters: [Character: Character] = [",
    ]
    lines.extend(emit_entries("", characters, lambda k, v: f"{swift_string_literal(k)}: {swift_string_literal(v)}"))
    lines.append("    ]")
    lines.append("")
    lines.append("    /// Traditional -> simplified phrase pairs, applied longest-match before characters.")
    lines.append("    static let phrases: [(source: String, target: String)] = [")
    lines.extend(
        emit_entries(
            "",
            phrases,
            lambda k, v: f"(source: {swift_string_literal(k)}, target: {swift_string_literal(v)})",
        )
    )
    lines.append("    ]")
    lines.append("}")

    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.output} ({len(characters)} chars, {len(phrases)} phrases)")


if __name__ == "__main__":
    main()
