openapi: 3.0.3
info:
  title: PromptMeet API
  description: 智能化实时会议纪要与日程同步系统 API 文档
  version: 0.1.0
  contact:
    name: PromptMeet Team
    email: team@promptmeet.com

servers:
  - url: http://localhost:8000
    description: 本地开发服务器
  - url: https://api.promptmeet.com
    description: 生产环境

paths:
  /health:
    get:
      summary: 健康检查
      description: 检查系统健康状态
      responses:
        '200':
          description: 系统正常
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  timestamp:
                    type: string
                    format: date-time
                  service:
                    type: string
                    example: PromptMeet Backend

  /api/transcribe:
    post:
      summary: 音频转写
      description: 上传音频文件或流式音频进行实时转写
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audio_file:
                  type: string
                  format: binary
                  description: 音频文件
                language:
                  type: string
                  default: zh
                  description: 音频语言代码
                enable_diarization:
                  type: boolean
                  default: true
                  description: 是否启用说话人识别
      responses:
        '200':
          description: 转写成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranscribeResponse'

  /api/extract:
    post:
      summary: 语义提取
      description: 从转写文本中提取任务、决议和关键信息
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transcript:
                  type: string
                  description: 转写的文本内容
                meeting_type:
                  type: string
                  enum: [general, standup, review, planning]
                  default: general
                  description: 会议类型
      responses:
        '200':
          description: 提取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtractResponse'

  /api/agent:
    post:
      summary: Agent问答
      description: 基于会议上下文进行智能问答
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: 用户问题
                meeting_id:
                  type: string
                  description: 会议ID，用于获取上下文
                context_window:
                  type: integer
                  default: 5
                  description: 上下文窗口大小
      responses:
        '200':
          description: 回答成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponse'

  /api/sync:
    post:
      summary: 平台同步
      description: 将任务和纪要同步到第三方平台
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                platform:
                  type: string
                  enum: [notion, feishu]
                  description: 目标平台
                meeting_id:
                  type: string
                  description: 会议ID
                sync_tasks:
                  type: boolean
                  default: true
                  description: 是否同步任务
                sync_notes:
                  type: boolean
                  default: true
                  description: 是否同步纪要
      responses:
        '200':
          description: 同步成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncResponse'

components:
  schemas:
    TranscribeResponse:
      type: object
      properties:
        transcript:
          type: string
          description: 转写文本
        segments:
          type: array
          items:
            type: object
            properties:
              speaker:
                type: string
                description: 说话人标识
              text:
                type: string
                description: 文本内容
              start_time:
                type: number
                description: 开始时间（秒）
              end_time:
                type: number
                description: 结束时间（秒）
        confidence:
          type: number
          description: 转写置信度

    ExtractResponse:
      type: object
      properties:
        summary:
          type: string
          description: 会议摘要
        tasks:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              assignee:
                type: string
              due_date:
                type: string
                format: date
              priority:
                type: string
                enum: [high, medium, low]
        decisions:
          type: array
          items:
            type: string
        action_items:
          type: array
          items:
            type: string

    AgentResponse:
      type: object
      properties:
        answer:
          type: string
          description: AI回答
        confidence:
          type: number
          description: 回答置信度
        sources:
          type: array
          items:
            type: string
          description: 信息来源

    SyncResponse:
      type: object
      properties:
        success:
          type: boolean
        platform:
          type: string
        synced_items:
          type: object
          properties:
            tasks_count:
              type: integer
            notes_count:
              type: integer
        links:
          type: array
          items:
            type: string
          description: 同步后的链接 